const themeBtn=document.getElementById('themeBtn'),refreshBtn=document.getElementById('refreshBtn'),leagueFilter=document.getElementById('leagueFilter'),daysFilter=document.getElementById('daysFilter'),searchInput=document.getElementById('searchInput'),matchesList=document.getElementById('matchesList'),liveList=document.getElementById('liveList'),nextList=document.getElementById('nextList'),apiStatus=document.getElementById('apiStatus'),officialWatchLink=document.getElementById('officialWatchLink'),cpaSideLink=document.getElementById('cpaSideLink');
const fields={statAll:document.getElementById('statAll'),statLive:document.getElementById('statLive'),statUpcoming:document.getElementById('statUpcoming'),statFinished:document.getElementById('statFinished'),heroLeague:document.getElementById('heroLeague'),heroHomeTeam:document.getElementById('heroHomeTeam'),heroAwayTeam:document.getElementById('heroAwayTeam'),heroHomeLogo:document.getElementById('heroHomeLogo'),heroAwayLogo:document.getElementById('heroAwayLogo'),heroScore:document.getElementById('heroScore'),heroTime:document.getElementById('heroTime'),selectedTitle:document.getElementById('selectedTitle'),homeTeam:document.getElementById('homeTeam'),awayTeam:document.getElementById('awayTeam'),homeLogo:document.getElementById('homeLogo'),awayLogo:document.getElementById('awayLogo'),scoreText:document.getElementById('scoreText'),competitionName:document.getElementById('competitionName'),matchTime:document.getElementById('matchTime'),matchStatus:document.getElementById('matchStatus'),statusSmall:document.getElementById('statusSmall'),lastUpdate:document.getElementById('lastUpdate'),autoArticle:document.getElementById('autoArticle')};
let allMatches=[],currentTab='ALL',selectedMatchId=null,watchLink='#';
themeBtn.onclick=()=>{document.body.classList.toggle('light');themeBtn.textContent=document.body.classList.contains('light')?'☀':'☾'};refreshBtn.onclick=loadMatches;leagueFilter.onchange=renderAll;daysFilter.onchange=loadMatches;searchInput.oninput=renderAll;document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentTab=btn.dataset.tab;renderAll()});
document.getElementById('copyMatchBtn').onclick=async()=>{const text=`${fields.homeTeam.textContent} ضد ${fields.awayTeam.textContent}\n${fields.competitionName.textContent}\n${fields.matchTime.textContent}\nالحالة: ${fields.statusSmall.textContent}\nالنتيجة: ${fields.scoreText.textContent}`;try{await navigator.clipboard.writeText(text);alert('تم نسخ تفاصيل المباراة')}catch{alert(text)}};
function formatDZTime(dateStr){if(!dateStr)return'غير محدد';return new Intl.DateTimeFormat('ar-DZ',{weekday:'short',hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit',timeZone:'Africa/Algiers'}).format(new Date(dateStr))+' - توقيت الجزائر'}
function onlyTime(dateStr){if(!dateStr)return'-';return new Intl.DateTimeFormat('ar-DZ',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Algiers'}).format(new Date(dateStr))}
function statusAr(status){return{SCHEDULED:'قادمة',TIMED:'قادمة',IN_PLAY:'مباشرة الآن',LIVE:'مباشرة الآن',PAUSED:'استراحة',FINISHED:'انتهت',POSTPONED:'مؤجلة',SUSPENDED:'متوقفة',CANCELED:'ملغاة'}[status]||status||'غير محدد'}
function matchGroup(m){if(['IN_PLAY','LIVE','PAUSED'].includes(m.status))return'LIVE';if(['SCHEDULED','TIMED'].includes(m.status))return'UPCOMING';if(m.status==='FINISHED')return'FINISHED';return'OTHER'}
function badgeClass(m){const g=matchGroup(m);return g==='LIVE'?'live':g==='UPCOMING'?'upcoming':g==='FINISHED'?'finished':''}
function scoreOf(m){const h=m.score?.fullTime?.home??m.score?.halfTime?.home,a=m.score?.fullTime?.away??m.score?.halfTime?.away;return h==null||a==null?'VS':`${h} - ${a}`}
function fallbackLogo(name){return`https://placehold.co/100x100/0f172a/22dc62?text=${encodeURIComponent((name||'?').slice(0,2).toUpperCase())}`}
function logoUrl(url,name){return url||fallbackLogo(name)}
async function loadConfig(){try{const r=await fetch('/api/config'),d=await r.json();watchLink=d.watchLink||'#';officialWatchLink.href=watchLink;cpaSideLink.href=watchLink}catch{}}
async function loadMatches(){matchesList.innerHTML='<div class="loading">جاري تحميل المباريات...</div>';apiStatus.textContent='جاري الاتصال بـ Netlify Function...';try{const days=Number(daysFilter.value||7),r=await fetch(`/api/matches?days=${days}&cache=${Date.now()}`),d=await r.json();if(!r.ok||d.error)throw new Error(d.message||'API Error');allMatches=d.matches||[];apiStatus.textContent=d.source==='demo'?'الموقع يعمل، لكن FOOTBALL_DATA_TOKEN غير موجود. يتم عرض ديمو.':`تم جلب ${d.count||allMatches.length} مباراة من ${d.source}.`;buildLeagueFilter();renderAll()}catch(e){matchesList.innerHTML='<div class="loading">حدث خطأ في جلب المباريات.</div>';apiStatus.textContent='خطأ: '+e.message}}
function buildLeagueFilter(){const cur=leagueFilter.value,map=new Map();allMatches.forEach(m=>{if(m.competitionCode)map.set(m.competitionCode,m.competition)});leagueFilter.innerHTML='<option value="ALL">كل البطولات</option>';[...map.entries()].sort((a,b)=>a[1].localeCompare(b[1])).forEach(([code,name])=>{const o=document.createElement('option');o.value=code;o.textContent=name;leagueFilter.appendChild(o)});if([...map.keys()].includes(cur))leagueFilter.value=cur}
function filteredMatches(){const l=leagueFilter.value,q=searchInput.value.trim().toLowerCase();return allMatches.filter(m=>l==='ALL'||m.competitionCode===l).filter(m=>currentTab==='ALL'||matchGroup(m)===currentTab).filter(m=>!q||`${m.homeTeam} ${m.awayTeam} ${m.competition}`.toLowerCase().includes(q)).sort((a,b)=>new Date(a.utcDate)-new Date(b.utcDate))}
function updateStats(){fields.statAll.textContent=allMatches.length;fields.statLive.textContent=allMatches.filter(m=>matchGroup(m)==='LIVE').length;fields.statUpcoming.textContent=allMatches.filter(m=>matchGroup(m)==='UPCOMING').length;fields.statFinished.textContent=allMatches.filter(m=>matchGroup(m)==='FINISHED').length}
function renderAll(){updateStats();renderMatches();renderCompactLists();const pref=allMatches.find(m=>matchGroup(m)==='LIVE')||allMatches.find(m=>matchGroup(m)==='UPCOMING')||allMatches[0];if(pref&&!selectedMatchId)selectMatch(pref)}
function renderMatches(){const list=filteredMatches();if(!list.length){matchesList.innerHTML='<div class="loading">لا توجد مباريات حسب هذا الاختيار.</div>';return}matchesList.innerHTML='';list.forEach(m=>{const c=document.createElement('article');c.className='match-card'+(m.id===selectedMatchId?' active':'');c.innerHTML=`<div class="card-top"><span class="competition">${m.competition}</span><span class="status-badge ${badgeClass(m)}">${statusAr(m.status)}</span></div><div class="card-teams"><div class="card-team"><img src="${logoUrl(m.homeLogo,m.homeTeam)}" alt="${m.homeTeam}" loading="lazy"><b>${m.homeTeam}</b></div><div class="card-score"><strong>${scoreOf(m)}</strong><small>${onlyTime(m.utcDate)}</small></div><div class="card-team"><img src="${logoUrl(m.awayLogo,m.awayTeam)}" alt="${m.awayTeam}" loading="lazy"><b>${m.awayTeam}</b></div></div>`;c.onclick=()=>selectMatch(m);matchesList.appendChild(c)})}
function renderCompactLists(){const live=allMatches.filter(m=>matchGroup(m)==='LIVE').slice(0,6),next=allMatches.filter(m=>matchGroup(m)==='UPCOMING').sort((a,b)=>new Date(a.utcDate)-new Date(b.utcDate)).slice(0,7);liveList.innerHTML=live.length?'':'<div class="empty">لا توجد مباريات مباشرة الآن.</div>';live.forEach(m=>liveList.appendChild(compactItem(m)));nextList.innerHTML=next.length?'':'<div class="empty">لا توجد مباريات قادمة.</div>';next.forEach(m=>nextList.appendChild(compactItem(m)))}
function compactItem(m){const d=document.createElement('div');d.className='compact-match';d.innerHTML=`<b>${m.homeTeam} ضد ${m.awayTeam}</b><small>${m.competition} - ${formatDZTime(m.utcDate)}</small><div class="compact-score">${scoreOf(m)} | ${statusAr(m.status)}</div>`;d.onclick=()=>selectMatch(m);return d}
function selectMatch(m){selectedMatchId=m.id;fields.heroLeague.textContent=m.competition;fields.heroHomeTeam.textContent=m.homeTeam;fields.heroAwayTeam.textContent=m.awayTeam;fields.heroHomeLogo.src=logoUrl(m.homeLogo,m.homeTeam);fields.heroAwayLogo.src=logoUrl(m.awayLogo,m.awayTeam);fields.heroScore.textContent=scoreOf(m);fields.heroTime.textContent=formatDZTime(m.utcDate);fields.selectedTitle.textContent=`تفاصيل مباراة ${m.homeTeam} و ${m.awayTeam}`;fields.homeTeam.textContent=m.homeTeam;fields.awayTeam.textContent=m.awayTeam;fields.homeLogo.src=logoUrl(m.homeLogo,m.homeTeam);fields.awayLogo.src=logoUrl(m.awayLogo,m.awayTeam);fields.scoreText.textContent=scoreOf(m);fields.competitionName.textContent=m.competition;fields.matchTime.textContent=formatDZTime(m.utcDate);fields.matchStatus.textContent=statusAr(m.status);fields.statusSmall.textContent=statusAr(m.status);fields.lastUpdate.textContent=new Intl.DateTimeFormat('ar-DZ',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Algiers'}).format(new Date());fields.autoArticle.innerHTML=`<p>يلتقي <b>${m.homeTeam}</b> مع <b>${m.awayTeam}</b> ضمن منافسات <b>${m.competition}</b>. موعد المباراة هو ${formatDZTime(m.utcDate)}، وحالة المباراة الحالية: <b>${statusAr(m.status)}</b>.</p><p>النتيجة الحالية: <b>${scoreOf(m)}</b>. يمكن للزوار متابعة التفاصيل من هذه الصفحة واستعمال زر المشاهدة للوصول إلى رابط رسمي أو عرض CPA.</p>`;renderMatches()}
async function init(){await loadConfig();await loadMatches();setInterval(loadMatches,5*60*1000)}init();
